/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { CarpoolGroupService } from "../carpoolGroup.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { CarpoolGroupCreateInput } from "./CarpoolGroupCreateInput";
import { CarpoolGroup } from "./CarpoolGroup";
import { CarpoolGroupFindManyArgs } from "./CarpoolGroupFindManyArgs";
import { CarpoolGroupWhereUniqueInput } from "./CarpoolGroupWhereUniqueInput";
import { CarpoolGroupUpdateInput } from "./CarpoolGroupUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class CarpoolGroupControllerBase {
  constructor(
    protected readonly service: CarpoolGroupService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: CarpoolGroup })
  @nestAccessControl.UseRoles({
    resource: "CarpoolGroup",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createCarpoolGroup(
    @common.Body() data: CarpoolGroupCreateInput
  ): Promise<CarpoolGroup> {
    return await this.service.createCarpoolGroup({
      data: {
        ...data,

        account: data.account
          ? {
              connect: data.account,
            }
          : undefined,
      },
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        groupName: true,

        account: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [CarpoolGroup] })
  @ApiNestedQuery(CarpoolGroupFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "CarpoolGroup",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async carpoolGroups(@common.Req() request: Request): Promise<CarpoolGroup[]> {
    const args = plainToClass(CarpoolGroupFindManyArgs, request.query);
    return this.service.carpoolGroups({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        groupName: true,

        account: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: CarpoolGroup })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "CarpoolGroup",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async carpoolGroup(
    @common.Param() params: CarpoolGroupWhereUniqueInput
  ): Promise<CarpoolGroup | null> {
    const result = await this.service.carpoolGroup({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        groupName: true,

        account: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: CarpoolGroup })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "CarpoolGroup",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateCarpoolGroup(
    @common.Param() params: CarpoolGroupWhereUniqueInput,
    @common.Body() data: CarpoolGroupUpdateInput
  ): Promise<CarpoolGroup | null> {
    try {
      return await this.service.updateCarpoolGroup({
        where: params,
        data: {
          ...data,

          account: data.account
            ? {
                connect: data.account,
              }
            : undefined,
        },
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          groupName: true,

          account: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: CarpoolGroup })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "CarpoolGroup",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteCarpoolGroup(
    @common.Param() params: CarpoolGroupWhereUniqueInput
  ): Promise<CarpoolGroup | null> {
    try {
      return await this.service.deleteCarpoolGroup({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          groupName: true,

          account: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
